/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mikebayles

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class TreesTest {

    //https://en.wikipedia.org/wiki/Tree_traversal
    val wikiTreeHead: BinaryNode = BinaryNode(
            data = "F",
            left = BinaryNode(
                    data = "B",
                    left = BinaryNode(data = "A"),
                    right = BinaryNode(
                            data = "D",
                            left = BinaryNode("C"),
                            right = BinaryNode("E")
                    )
            ),
            right = BinaryNode(
                    data = "G",
                    right = BinaryNode(
                            data = "I",
                            left = BinaryNode("H")
                    )
            )
    )

    @Test
    fun `in order traversal`() {
        val result = mutableListOf<String>()
        inOrderTraversal(result, wikiTreeHead)

        assertEquals(mutableListOf("A", "B", "C", "D", "E", "F", "G", "H", "I"), result)
    }

    @Test
    fun `pre order traversal`() {
        val result = mutableListOf<String>()
        preOrderTraversal(result, wikiTreeHead)

        assertEquals(mutableListOf("F", "B", "A", "D", "C", "E", "G", "I", "H"), result)
    }

    @Test
    fun `post order traversal`() {
        val result = mutableListOf<String>()
        postOrderTraversal(result, wikiTreeHead)
        
        assertEquals(mutableListOf("A", "C", "E", "D", "B", "H", "I", "G", "F"), result)
    }
}
